services:
  nest-demo:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes: 
      - .:/usr/src/app
    env_file:
      - .env.development
    depends_on:
      - postgres
    networks:
      - app-networks

  postgres:
    image: postgres:15
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Lala12345.
      POSTGRES_DB: proyecto_M4
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-networks

volumes:
  postgres-data:

networks:
  app-networks:
